### ISSUE TITLE
Dubbla användarkonton efter att STIL blivit del av LUCAT

### ISSUE THREAD

**Issue by Mahnas92** [AlexanderEkdahl/bokhyllan.lu#35]
Jag kan inte längre nå och ta bort annonser gjorda innan LU gjorde förändringar på inloggningssystemet.

Som det ser ut så har ett nytt "konto" (rent tekniskt) skapats i och med första inloggningen med det nya systemet, och därmed har man (i alla fall jag) blivit utestängd från det "gamla kontot".

Kontaktas ständigt av folk som vill köpa böcker som jag redan sålt utan att kunna ta bort annonsen...

**Comment by AlexanderEkdahl** [comment]
Andra användare stöter inte på samma problem. Jag har dock tagit bort din annons för "Fysik i vätskor och gaser" nu.

**Comment by Mahnas92** [comment]
Det är konstigt. Men du kan väl se att jag har problem från din sida eller? 

Ps, vill du vänligen även ta bort denna annons
https://bokhyllan.lu/items/20-vaglara-och-optik/orders/2020

**Comment by AlexanderEkdahl** [comment]
Efter lite detektivarbete ser jag att du har en användare med email "ada10mna @student.lu.se" och en som är "ada10mna@student.lu.se"(notera mellan innan @). Jag tog bort den felaktiga användaren.

**Comment by AlexanderEkdahl** [comment]
Jag ska undersöka närmare hur det kunde bli så!

**Comment by Mahnas92** [comment]
Märker också att du endast tog bort annonsen från mitt "nya konto" som skulle indikera att den gamla (se länk) var såld. 
https://bokhyllan.lu/items/184-fysik-i-vatskor-och-gaser/orders/2179

**Comment by Mahnas92** [comment]
Hmm, det felaktiga  felaktiga kontot, är det det gamla? 
För jag kan inte längre hitta alla annonser som jag har...

**Comment by AlexanderEkdahl** [comment]
När jag tog bort ditt gamla konto så försvann alla annonser som du inte längre kunde ta bort. Om du har några böcker där som du fortfarande vill sälja är det fritt fram att skapa annonserna igen med det nya kontot.

Böckerna som du hade annonser för var:

- Electrical Engineering principles and applications
- Objects, Abstraction, Data Structures and Design using Java
- Våglära och Optik
- Analys I En Variabel
- Extreme Programming Pocket Guide
- Data Communications and Networking
