### ISSUE TITLE
bokhyllan.lu not reachable

### ISSUE THREAD

**Issue by skogsbrus** [AlexanderEkdahl/bokhyllan.lu#39]
"Server not found" error when connecting to https://bokhyllan.lu/

**Comment by AlexanderEkdahl** [comment]
This is because the domain has expired. We are both in the process of graduating, and there seemed to be very little interest in anyone taking over the maintenance. The service is still reachable at https://bokhyllan.herokuapp.com.

**Comment by ErikBjare** [comment]
@AlexanderEkdahl I just bought back the domain name. Is it sufficient to make a CNAME record that points to `bokhyllan.herokuapp.com`?

**Comment by AlexanderEkdahl** [comment]
Yes, however, the instructions may have changed. The code is hosted on Heroku and it is their specific instructions. I’m glad to hear that you bought back the domain. 

If you have any other questions. Don’t hesitate to contact me.

**Comment by ErikBjare** [comment]
I pointed the domain www.bokhyllan.lu to bokhyllan.herokuapp.com

Needed some DNS black magic since my registrar doesn't support ALIAS entries but it works now with the www subdomain.

However, it seems like the SSL certificate isn't valid for the domain. Do you know how to fix this?

**Comment by AlexanderEkdahl** [comment]
Transfer your domain to Cloudflare and use their service.

**Comment by ErikBjare** [comment]
Alright, on it.

**Comment by ErikBjare** [comment]
Works great now. This issue can be closed.

Thanks for the Cloudflare tip @AlexanderEkdahl, will come in handy for other domains I manage. (I should have tried it earlier)
