### ISSUE TITLE
Transfer ownership to Code@LTH

### ISSUE THREAD

**Issue by ErikBjare** [AlexanderEkdahl/bokhyllan.lu#40]
We got an email from @joacimastrom that asked if we wanted to take over the maintenance of the website a while back. I just bought back the domain name (see https://github.com/AlexanderEkdahl/bokhyllan.lu/issues/39) and think we have people interested in the small amount of work required to keep it afloat.

Do you think it would be reasonable to move the repository to the @Code-at-LTH org or do you wish to keep it under your namespace @AlexanderEkdahl ?

**Comment by AlexanderEkdahl** [comment]
No, we can move it to another organization. However, I’d like to go through it and see if there’s anything that should be changed. I’ll try to look at it this weekend.

**Comment by Powersource** [comment]
Any update on this? Would we be able to transfer ownership of e.g. heroku too?

**Comment by ErikBjare** [comment]
:+1: for Heroku access
